const entrada = [
    "hola",
    "hola buenos dias",
    "hola buenas tardes",
    "hola buenas noches",
    "buenos dias",
    "buenas tardes",
    "buenas noches",
    "hola orbyt",
    "adios",
    "gracias",
    "que cosas puedes hacer",
    "que haces",
    "que servicios ofreces",
    "que tareas puedes realizar",
    "cuales son tus capacidades",
    "que funciones tienes disponibles",
    "que puedes hacer por mí",
    "que opciones tienes",
    "que tipo de cosas puedes hacer",
    "que habilidades tienes",
    "cuales son tus funcionalidades",
    "que tareas puedes ejecutar",
    "agregar nota",
    "me agregas una nota",
    "me haces una nota",
    "puedes añadir una nota por favor",
    "podrias agregar una nueva nota",
    "me ayudas a guardar una nota",
    "podrias anotar algo para mi" ,
    "te encargarias de añadir una nota",
    "me puedes escribir una nota",
    "me haces el favor de agregar una nota",
    "puedes registrar una nota para mi",
    "te importaría añadir una nota",
    "agregar una nota",
    "agregar una tarea",
    "agregar tarea",
    "me agregas una tarea",
    "puedes añadir una tarea por favor",
    "podrias agregarme una nueva tarea",
    "te importaria anotar una tarea para mi",
    "me ayudas a incluir una tarea",
    "me haces el favor de agregar una tarea",
    "podrias registrar una tarea",
    "me puedes añadir una tarea a la lista",
    "puedes incluir una tarea para mi",
    "te encargarias de agregar una tarea",
    "puedes crear una tarea nueva",
    "agregar recordatorio",
    "agregar un recordatorio",
    "me agregas un recordatorio",
    "puedes añadir un recordatorio por favor",
    "podrias agregarme un nuevo recordatorio",
    "me ayudas a incluir un recordatorio",
    "te importaria anotar un recordatorio para mi",
    "me haces el favor de agregar un recordatorio",
    "podrias registrar un recordatorio",
    "me puedes añadir un recordatorio a la lista",
    "puedes incluir un recordatorio para mi",
    "te encargarias de agregar un recordatorio",
    "puedes crear un nuevo recordatorio",
    "puedes enseñarme mis tareas",
    "me podrias mostrar mis tareas",
    "quiero ver mis tareas",
    "puedes mostrarme la lista de mis tareas",
    "me ayudas a ver mis tareas",
    "puedes darme un vistazo a mis tareas",
    "me gustaria revisar mis tareas",
    "me enseñas las tareas que tengo",
    "puedes compartir mis tareas conmigo",
    "me muestras las tareas pendientes",
    "puedes enseñarme mis notas",
    "me podrias mostrar mis notas",
    "quiero ver mis notas",
    "puedes mostrarme la lista de mis notas",
    "me ayudas a ver mis notas",
    "puedes darme un vistazo a mis notas",
    "me gustaria revisar mis notas",
    "me enseñas las notas que tengo",
    "puedes compartir mis notas conmigo",
    "me muestras las notas guardadas",
    "puedes enseñarme mis recordatorios",
    "me podrias mostrar mis recordatorios",
    "quiero ver mis recordatorios",
    "puedes mostrarme la lista de mis recordatorios",
    "me ayudas a ver mis recordatorios",
    "puedes darme un vistazo a mis recordatorios",
    "me gustaria revisar mis recordatorios",
    "me enseñas los recordatorios que tengo",
    "puedes compartir mis recordatorios conmigo",
    "me muestras los recordatorios pendientes",
    

  
];






